server:
  port: ${SERVER_PORT:9090}

spring:
  datasource:
    url: jdbc:h2:file:~/to_go_fit
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
logging:
  level:
    org:
      springframework: WARN
